In [2]:
#Question #1

import numpy as np

x=np.array([1,2,3,4])

y=x.tolist()
print(y,type(y))

[1, 2, 3, 4] <class 'list'>


In [3]:
#Question #2
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
trace=np.trace(x)
print(x)
print(f"Sum = {trace}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum = 15


In [7]:
#Question #3
import numpy as np

a = np.array([[1,2],[3,5]])
x=2

for i in range(len(a)):
    for j in range(len(a[0])):
        if a[i,j]>x:
            print(a[i,j],end=" ")

3 5 

In [8]:
#Question #4
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

c=np.add(a,b)
print(c)

[[ 6  8]
 [10 12]]


In [9]:
#Question #5
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean=np.mean(x,axis=1)

for i in range(len(x)):
    m=x[i]-mean[i]
    print(m)

[-1.  0.  1.]
[-1.  0.  1.]
[-1.  0.  1.]
